@echo off
set VITE_SUPABASE_URL=https://jixqdgldndtbbcqzenxl.supabase.co
set VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppeHFkZ2xkbmR0YmJjcXplbnhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ5NzU1NzgsImV4cCI6MjA4MDU1MTU3OH0.XUSyBaztNPmCK_v6ZhEg1lAkCU-DbHdVO9cFMYNhBcw
npx tsx scripts/add-streamers.ts
